# -*- coding: utf-8 -*-
"""navie_bayes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1co8o6HBaxLCnq8Y908uW_EZxM5ob9P-y
"""

import numpy as np
import pandas as pd
import csv

import urllib
import sklearn
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB

from sklearn.model_selection import train_test_split


from sklearn import metrics
from sklearn.metrics import accuracy_score

"""**NAVIE** **BAYES**

Loading the dataset
"""

url = 'https://raw.githubusercontent.com/Yash-Nagda/COVID_19/master/try_num.csv?token=ALVYLO4EDGKJF3YYPUHWMAK64MO6Y'
df = pd.read_csv(url)

"""split into parameters and class"""

dfs = np.split(df, [20], axis=1)
X=dfs[0]
y=dfs[1]

"""spilt data for training and testing"""

X_train, X_test, y_train, y_test = train_test_split (X, y, test_size=.7, random_state=42)

"""**Bernoulli Model**"""

BernNB = BernoulliNB (binarize=True)
BernNB.fit(X_train,y_train)
print(BernNB)

y_expect=y_test
y_pred=BernNB.predict(X_test)
print (accuracy_score(y_expect,y_pred))

"""**Multinomial Model**"""

MultiNB = MultinomialNB ()

MultiNB.fit (X_train, y_train) 
print (MultiNB)

y_pred = MultiNB.predict(X_test)
print (accuracy_score(y_expect, y_pred))

"""**Gaussian** **Model**"""

GausNB = GaussianNB ()

GausNB.fit (X_train, y_train)

print (GausNB)

y_pred = GausNB.predict (X_test)
print (accuracy_score(y_expect,y_pred))